### ISSUE TITLE
不具合疑義：SVGファイルを読み込むと画像が表示されない

### ISSUE THREAD

**Issue by B-biker** [Mafty-Hs/Udonite-Server#2]
失礼いたします。
自宅環境にてUdoniteを動かしていたところ、表記の事象を確認致しました。
以下に詳細を記載致します。
下名環境での設定不備が原因の可能性もありますので
確認していただけると幸いです。

### 不具合疑義内容
画像としてSVGファイルを読み込むと画像が表示されない

### 再現方法

1. ロビーページにアクセスする
2. 空き部屋の「新規作成」ボタンを押下する
3. 「新しいルームを作成」ボタンを押下する
4. 新規プレイヤーで「ルームに入室」ボタンを押下する
5. 「ファイル」→「画像」にて画像ウィンドウを表示する
6. 「ここに画像をドロップ」に後述のsvgファイルをドロップする

### 結果
画像が表示されず、リンク切れのような形で表示される

### 期待する結果
svg画像が表示される
本家Udonariumと同様の動作

### 使用したサンプルデータ
次の画像素材をSVG形式でダウンロードして使用しております
https://icooon-mono.com/10688-%e5%89%a3%e3%81%ae%e3%82%a2%e3%82%a4%e3%82%b3%e3%83%b3/

### 推察される原因
src/core/udonarium/image-storage.ts内のuploadメソッドおよびthumbnailメソッドにおいて
アップロード後のファイル名の拡張子をMIMEタイプから取得しているようですが
その際、svgファイルのMIMEタイプはimage/svg+xmlとなり
アップロードされるファイルの拡張子が"svg"ではなく"svg+xml"となるようです。
これにより正常にsvg画像として認識されなくなっているものと推察しております。

下名独自でuploadメソッドおよびthumbnailメソッドを
以下のように修正することで正常動作することを確認しております。
但しこれが妥当な解決方法かは判断付きませんでしたので、issueとさせて頂いております。

```
  private async upload(file :ArrayBuffer, type :string, hash :string) {
    let fileExtension = type.substring(type.indexOf('/') + 1);
    if(fileExtension == 'svg+xml'){
      fileExtension='svg';
    }
    let filename = hash + '.' + fileExtension;
    let writePath = this.imagePath + "/" + filename;
    try {
      let writeStream = fs.createWriteStream(writePath);
      await new Promise<void>((resolve,reject) => {
        writeStream.write(file,'binary');
        writeStream.end(resolve);
      })
    }
    catch(error) {
      errorLog("image write error",this.room.roomId,error)
      return "";
    }
    return this.imageUrl + "/" + filename;
  }

  private async thumbnail(type :string, hash :string) {
    let fileExtension = type.substring(type.indexOf('/') + 1);
    if(fileExtension == 'svg+xml'){
      fileExtension='svg';
    }
    let filename = hash + '.' + fileExtension;
    let thumbnail = await sharp(this.imagePath + "/" + filename)
      .resize({
        width: 128,
        height: 128,
        fit: "outside"
      })
      .toBuffer();
    let writePath = this.imagePath + "/thumb/" + filename;
    let writeStream = fs.createWriteStream(writePath);
    await new Promise<void>((resolve,reject) => {
      writeStream.write(thumbnail,'binary');
      writeStream.end(resolve);
    })
    return  this.imageUrl + "/" + "thumb/" + filename;
  }
```

### 実行環境
**クライアント機：**
Windows 11 Home 21H2(OSビルド22000.613、Windows 機能エクスペリエンス パック 1000.22000.613.0)
Google Chrome : 100.0.4896.127（Official Build） （64 ビット）

**サーバー機：**
Ubuntu 22.04 LTS (GNU/Linux 5.15.0-27-generic x86_64)
nginx version: nginx/1.18.0 (Ubuntu)
Angular CLI: 13.2.6
Node: 16.14.2
Package Manager: npm 8.5.0
MongoDB server version: 5.0.8
Udonite 1.1.1
udonite-server 1.0.8

**Comment by Mafty-Hs** [comment]
報告ありがとうございます。
その原因なのであればユドナリウムが内蔵しているMimeTypeライブラリをサーバ側に移植することで対応できそうです。
udonite-server 1.0.9で対応します。
